const app=require('express');
const router=app.Router();
const {createCatagory,getAllCatagory}=require("../controllers/CatagoryCT");
const {isAdmin,auth,isInstructor}=require("../middlewares/middlewareAuth");
const {createCourse,getAllCourseDetail}=require("../controllers/CourseCT");
const {createSection}=require("../controllers/SectionCT");
const{createSubSection}=require("../controllers/Sub-SectionCT");
router.post("/createCatagory",auth,isAdmin,createCatagory);
router.get("/getAllCatagory",auth,isAdmin,getAllCatagory);
router.post("/createCourse",auth,isInstructor,createCourse);
router.get("/getAllCourseDetail",auth,isInstructor,getAllCourseDetail);
router.post("/createSection",auth,isInstructor,createSection);
router.post("/createSubSection",auth,isInstructor,createSubSection);
module.exports=router;